/*
 * Principal.java
 *
 */

package comissao.view;

import javax.swing.JOptionPane;


/**
 *
 * @author  clayton
 */
public class Principal extends javax.swing.JFrame {
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAluosView = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnGerar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnImprimir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnSair = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        imAlunos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        imQuitar = new javax.swing.JMenuItem();
        jMenuOpcao = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Contas - Comissão de formatura");

        jToolBar1.setFloatable(false);
        jToolBar1.setAutoscrolls(true);
        jToolBar1.setMinimumSize(new java.awt.Dimension(151, 90));
        jToolBar1.setPreferredSize(new java.awt.Dimension(167, 80));
        jToolBar1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                resize(evt);
            }
        });

        btnAluosView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/user-32.png"))); // NOI18N
        btnAluosView.setFocusable(false);
        btnAluosView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAluosView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAluosView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluosViewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAluosView);
        jToolBar1.add(jSeparator2);

        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/money-32.png"))); // NOI18N
        btnGerar.setFocusable(false);
        btnGerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGerar);
        jToolBar1.add(jSeparator3);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/print.png"))); // NOI18N
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimir);
        jToolBar1.add(jSeparator4);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/exit-32.png"))); // NOI18N
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        Cadastros.setMnemonic('C');
        Cadastros.setText("Cadastros");

        imAlunos.setMnemonic('a');
        imAlunos.setText("Alunos");
        imAlunos.setAlignmentX(50.0F);
        imAlunos.setAlignmentY(50.0F);
        imAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imAlunosActionPerformed(evt);
            }
        });
        Cadastros.add(imAlunos);

        jMenuBarPrincipal.add(Cadastros);

        jMenu1.setText("Boletos");

        jMenuItem2.setText("Gerar boletos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        imQuitar.setText("Quitar boletos");
        imQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imQuitarActionPerformed(evt);
            }
        });
        jMenu1.add(imQuitar);

        jMenuBarPrincipal.add(jMenu1);

        jMenuOpcao.setMnemonic('O');
        jMenuOpcao.setText("Opções");
        jMenuOpcao.setToolTipText("Opções do Programa");

        jMenuItem1.setText("Configurações");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuOpcao.add(jMenuItem1);
        jMenuOpcao.add(jSeparator1);

        jMenuBarPrincipal.add(jMenuOpcao);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imAlunosActionPerformed
        // TODO add your handling code here:
        new AlunoView(this, true).setVisible(true);

}//GEN-LAST:event_imAlunosActionPerformed

private void btnAluosViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluosViewActionPerformed
    imAlunosActionPerformed(evt);
}//GEN-LAST:event_btnAluosViewActionPerformed

private void resize(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_resize
    // TODO add your handling code here:
    jToolBar1.setSize(this.getWidth(), 48);
}//GEN-LAST:event_resize

private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
// TODO add your handling code here:
    int var = JOptionPane.showConfirmDialog(null, "Deseja sair ?", "Deseja realmente excluir ?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

    if (var == 0) {
        System.exit(0);      
    }
}//GEN-LAST:event_btnSairActionPerformed

private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
// TODO add your handling code here:
    jMenuItem2ActionPerformed(evt);
    
}//GEN-LAST:event_btnGerarActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
        new ConfiguracaoView(this, true).setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    new GeraBoletoView(this, true).setVisible(true);
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
// TODO add your handling code here:
    imQuitarActionPerformed(evt);
}//GEN-LAST:event_btnImprimirActionPerformed

private void imQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imQuitarActionPerformed
// TODO add your handling code here:
    new QuitacaoEmissaoBoletoView(this, true).setVisible(true);
}//GEN-LAST:event_imQuitarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastros;
    private javax.swing.JButton btnAluosView;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem imAlunos;
    private javax.swing.JMenuItem imQuitar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuOpcao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
