/*
 * QuitacaoEmissaoBoleto.java
 *
 * Created on 5 de Agosto de 2008, 04:47
 */

package comissao.view;

import comissao.controller.BoletoController;
import comissao.controller.ConfiguracaoController;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  clayton
 */
public class QuitacaoEmissaoBoletoView extends javax.swing.JDialog {

    /** Creates new form QuitacaoEmissaoBoleto */
    public QuitacaoEmissaoBoletoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

       

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnImprimir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnQuitar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quitação de Boletos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setName("jToolBar1"); // NOI18N

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnImprimir.setName("btnImprimir"); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimir);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jToolBar1.add(jSeparator3);

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/money-32.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.setFocusable(false);
        btnQuitar.setName("btnQuitar"); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuitar);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comissao/view/images/exit-32.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setFocusable(false);
        btnFechar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setVerifyInputWhenFocusTarget(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFechar);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setName("jPanel1"); // NOI18N

        lblMensagem.setText("     ");
        lblMensagem.setName("lblMensagem"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblMensagem)
                .addContainerGap(796, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lblMensagem))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
private void carregaTabela(){
     Vector<String> vetColunas = new Vector<String>();
    vetColunas.addElement("Boleto"); 
    vetColunas.addElement("Aluno");
    vetColunas.addElement(" ");    
    vetColunas.addElement("Valor");
    vetColunas.addElement("Data de Emissão");
    vetColunas.addElement("Data de Quitação");
    vetColunas.addElement("Emitido");    
    objTableModel = new DefaultTableModel(vetColunas, 0);
    objTableModel = BoletoController.getBoletos(objTableModel);
    jTable1.setModel(objTableModel);
}    
    

private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
// TODO add your handling code here:
    
    lblMensagem.setText("Gerando boleto...");
    String linhaSel = String.valueOf(jTable1.getSelectedRow());

    BoletoController boleto = new BoletoController();

    ArrayList<String> dadosBoleto = new ArrayList<String>();

    ConfiguracaoController config = new ConfiguracaoController();


    dadosBoleto.add(config.getConfiguracao().getCedente());
    dadosBoleto.add(String.valueOf(jTable1.getValueAt(Integer.parseInt(linhaSel), 3)));
    dadosBoleto.add(String.valueOf(jTable1.getValueAt(Integer.parseInt(linhaSel), 2)));
    dadosBoleto.add(String.valueOf(jTable1.getValueAt(Integer.parseInt(linhaSel), 4)));
    dadosBoleto.add(Integer.toString(config.getConfiguracao().getBanco()));

    if (boleto.geraBoleto(dadosBoleto)) {
        String vIdBoleto = String.valueOf(jTable1.getValueAt(Integer.parseInt(linhaSel), 0));            
        boleto.setImpresso(vIdBoleto);
        String Msg = "Boleto gerado com sucesso!";
        JOptionPane.showMessageDialog(null, Msg, "Mensagem", JOptionPane.INFORMATION_MESSAGE);
    };
    


}//GEN-LAST:event_btnImprimirActionPerformed

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
// TODO add your handling code here:
    String linhaSel = String.valueOf(jTable1.getSelectedRow());
    String vIdBoleto = String.valueOf(jTable1.getValueAt(Integer.parseInt(linhaSel), 0));    
    
    BoletoController boleto = new BoletoController();
    boleto.quitarBoleto(vIdBoleto);
    
    carregaTabela();
    
    String Msg = "Quitação do boleto registrada.";    
    JOptionPane.showMessageDialog(null, Msg, "Mensagem", JOptionPane.INFORMATION_MESSAGE);

    
    
}//GEN-LAST:event_btnQuitarActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
 carregaTabela();
}//GEN-LAST:event_formWindowActivated

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
    
}//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuitacaoEmissaoBoletoView dialog = new QuitacaoEmissaoBoletoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    DefaultTableModel objTableModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnFechar;
    protected javax.swing.JButton btnImprimir;
    protected javax.swing.JButton btnQuitar;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToolBar.Separator jSeparator1;
    protected javax.swing.JToolBar.Separator jSeparator3;
    protected javax.swing.JTable jTable1;
    protected javax.swing.JToolBar jToolBar1;
    protected javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables

}


